#!/bin/bash
mkdir /var/mobile/Media/Succession/
chmod 0777 /var/mobile/Media/Succession/
killall SuccessionRestore
echo "Succession by Sam Gardner // Samg_is_a_Ninja"
echo "Special Thanks to MidnightChips, pwn20wnd, Cryptiiic, PsychoTea, uroboro, and 4ppleCracker"

exit 0
